name: deploy

on:
  workflow_dispatch:

jobs:

  pypi:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    env:
      PIP_INDEX_URL: 'https://:2023-04-16@time-machines-pypi.sealsecurity.io/'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Package
        run: |
          pip install --upgrade build
          echo "hatchling==1.14.0" > "${RUNNER_TEMP}/build-constraints.txt"
          PIP_CONSTRAINT="${RUNNER_TEMP}/build-constraints.txt" python -m build -s -w
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist/*
          if-no-files-found: error
